Fix invalid settings
These are reported by new feature that landed in golangci-lint v1.57:
`config verify`. I verified that there's no errors reported in current
mctl while messing with this file. Some of the features were removed
instead of put into the right place since they were not actually being
used and thus unnecessary.

In some cases I needed to figure out the correct setting/tweak and
referred to [1] for some more information.

Here's the list of errors reported by golangci-lint config verify before
these fixes:
```
go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57 config verify --config .golangci.yml
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
jsonschema: "linters-settings.govet" does not validate with "/properties/linters-settings/properties/govet/additionalProperties": additionalProperties 'auto-fix', 'check-shadowing' not allowed
jsonschema: "linters-settings.depguard" does not validate with "/properties/linters-settings/properties/depguard/additionalProperties": additionalProperties 'list-type' not allowed
jsonschema: "linters-settings.revive" does not validate with "/properties/linters-settings/properties/revive/additionalProperties": additionalProperties 'min-confidence' not allowed
jsonschema: "linters-settings.whitespace" does not validate with "/properties/linters-settings/properties/whitespace/additionalProperties": additionalProperties 'auto-fix' not allowed
jsonschema: "linters-settings.misspell" does not validate with "/properties/linters-settings/properties/misspell/additionalProperties": additionalProperties 'auto-fix' not allowed
jsonschema: "run" does not validate with "/properties/run/additionalProperties": additionalProperties 'skip-dirs', 'skip-files' not allowed
jsonschema: "" does not validate with "/additionalProperties": additionalProperties 'exclude-use-default', 'service' not allowed
Error: the configuration contains invalid elements
````

1: https://github.com/golangci/golangci-lint/blob/v1.57.0/.golangci.reference.yml